#!/usr/bin/env bash
set -euo pipefail

[[ -n "${DEBUG:-}" ]] && set -x

SCRIPT_NAME="$(basename "$(realpath "$0")")"
SCRIPT_VERSION='v0.0.2'
SCRIPT_AUTHOR='cloudygreybeard'
SCRIPT_SPDX_LICENSE_IDENTIFIER='Apache-2.0'


### Conf

: "${DOWNLOAD_DIR:=${HOME}/Work Folders/Downloads}"

KUBECONFIG_MARKER="aro-$(tr -dc a-z0-9 </dev/urandom | head -c 5 || true)"  # Windows appears not to like symlinks: they just end up as copied files. We tag our links with a marker for dealing with later. #yay-kludge
KUBECONFIG_MARKER_REGEX='aro-[a-z0-9]\{5\}'
KUBECONFIG_FILEEXT='kubeconfig'

LINK_NAME=
OPT_REALLY=


### Funcs

print_help() {
  cat >&2 <<EOF

Name: ${SCRIPT_NAME}
Version: ${SCRIPT_VERSION}
Author: ${SCRIPT_AUTHOR}
SPDX-License-Identifier: ${SCRIPT_SPDX_LICENSE_IDENTIFIER}


Usage:

  ${SCRIPT_NAME} [NAME]

    Finds most recent .${KUBECONFIG_FILEEXT} file in "${DOWNLOAD_DIR}", then
      - with NAME, creates a symlink to the kubeconfig file at NAME and prints its path; or
      - without NAME, prints the path to the kubeconfig file.

    Note: this is heinously kludged in order to work around Windows' use of file copies in
    place of symlinks: we match against a tag between name and file extension (regex:
    "\.aro-[a-z0-9]\{5\}", followed by fileext ".${KUBECONFIG_FILEEXT}"). This isn't pretty.


  ${SCRIPT_NAME} --list STRING [...STRING]
    Finds most recent .${KUBECONFIG_FILEEXT} files in "${DOWNLOAD_DIR}" matching STRINGs in
    previously created symlinks (matching kludgy regex; see above).

  ${SCRIPT_NAME} --purge [--yes-really]

    Finds and deletes previously created symlinked .${KUBECONFIG_FILEEXT} files in "${DOWNLOAD_DIR}".
    With --yes-really, don't prompt for each deletion. Even less pretty.


  ${SCRIPT_NAME} --print-wrapper

    Prints a function which may be used as a wrapper from .bash_profile or similar.
    This function exports KUBECONFIG from the result of \`command k-mostrecent [NAME]\`

EOF
  exit ${1:-}
}

purge() {
  RM_ARGS=( "--verbose" )
  [[ -z "${OPT_REALLY}" ]] && RM_ARGS+=( "--interactive=always" )
  find "${DOWNLOAD_DIR}" -maxdepth 1 -mindepth 1 -type f -regextype sed -regex ".*\.${KUBECONFIG_MARKER_REGEX}\.${KUBECONFIG_FILEEXT}" -exec rm "${RM_ARGS[@]}" '{}' \; >&2
  exit ${1:-}
}

print_wrapper() {
  cat >&2 <<'EOF'
k-mostrecent() {
  if new_kubeconfig="$(command k-mostrecent "$@")"; then
    export KUBECONFIG="${new_kubeconfig}"
    echo "${KUBECONFIG}"
  fi
  unset new_kubeconfig
}
EOF
  exit ${1:-}
}

find_existing_link() {
  find "${DOWNLOAD_DIR}" -maxdepth 1 -mindepth 1 -type f -regextype sed -regex ".*/${1:-}\.${KUBECONFIG_MARKER_REGEX}\.${KUBECONFIG_FILEEXT}" -printf "%T@ %p\n" | sort -n | cut -d\  -f2- | tail -n1
}

list_files() {
  local link_name
  for link_name in "$@"; do
    find_existing_link "${link_name}"
  done
  exit
}


### Main

while [[ ${1+\*} ]]; do   # while $1 is defined (and allows for null values etc)
  case "$1" in
    --help          ) print_help 2;;
    --yes-really    ) OPT_REALLY=1;;
    --purge         ) purge 42;;
    --print-wrapper ) print_wrapper 42;;
    --list          ) shift; list_files "$@";;
    *               ) LINK_NAME="${1:-}";;
  esac
  shift
done

KUBECONFIG_MOSTRECENT="$(find "${DOWNLOAD_DIR}" -maxdepth 1 -mindepth 1 -type f -regextype sed ! -regex ".*\.${KUBECONFIG_MARKER_REGEX}\.${KUBECONFIG_FILEEXT}" -regex ".*\.${KUBECONFIG_FILEEXT}" -printf "%T@ %p\n" | sort -n | cut -d\  -f2- | tail -n1)"

[[ -n "${KUBECONFIG_MOSTRECENT}" ]] || { echo "Could not find kubeconfig in ${DOWNLOAD_DIR}. Aborting." >&2; exit 1; }

if [[ -n "${LINK_NAME:-}" ]]; then
  KUBECONFIG_TARGET="$(find_existing_link "${LINK_NAME}")"
  if [[ ! -n "${KUBECONFIG_TARGET}" ]]; then
    # No match found. Create symlink.
    KUBECONFIG_TARGET="${DOWNLOAD_DIR}/${LINK_NAME}.${KUBECONFIG_MARKER}.${KUBECONFIG_FILEEXT}"
    ln -s "${KUBECONFIG_MOSTRECENT}" "${KUBECONFIG_TARGET}"
  fi
else
  # LINK_NAME not given. Just use most recent found without creating symlink.
  KUBECONFIG_TARGET="${KUBECONFIG_MOSTRECENT}"
fi

if [[ -e "${KUBECONFIG_TARGET}" ]]; then
  echo "${KUBECONFIG_TARGET}"
else
  echo "Could not create ${KUBECONFIG_TARGET}. Aborting." >&2
  exit 1
fi
